CONFIG = {
    'INITIAL_BALANCE': 10000,
    'LOOKBACK_PERIOD': 30,
    'HMM_COMPONENTS': 3,
    'MACD_FAST': 12,
    'MACD_SLOW': 26,
    'MACD_SIGNAL': 9,
    'PAIRS_WINDOW': 20,
    'PAIRS_ZSCORE_THRESHOLD': 1.0,
    'RNN_EPOCHS': 50,
    'RNN_BATCH_SIZE': 32
}
